### ISSUE TITLE
Issue when trying to build

### ISSUE THREAD

**Issue by Infisrael** [Gopro336/3arthh4ck_1.3.1-BUILDABLE-SRC#16]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Infisrael\Desktop\3arthh4ck-main\build.gradle' line: 50

* What went wrong:
A problem occurred evaluating root project '3arthh4ck-main'.
> C:\Users\Infisrael\Desktop\3arthh4ck-main\.git\HEAD (The system cannot find the path specified)

**Comment by Intel-i80486-DX4** [comment]
git clone it. (git clone https://github.com/Gopro336/3arthh4ck_1.3.1-BUILDABLE-SRC.git)

**Comment by Gopro336** [comment]
should be fixed
